binary_sensor:

  # Start MCP23017 Chip number 1 - 14 zones
  # Zone 01 Input
  - platform: gpio
    id: zone1
    name: 1_MasterBathWd
    icon: mdi:window-closed
    #state_topic: ${name}/binary_sensor/zone1/state
    pin:
      mcp23xxx: mcp23017_1
      number: 8
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 02 Input
  - platform: gpio
    name: 2_TVBackDoor
    id: zone2
    icon: mdi:door
    pin:
      mcp23xxx: mcp23017_1
      number: 9
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time


  # Zone 03 Input
#  - platform: gpio
#    name: Zone 03
#    id: zone3
#    pin:
#      mcp23xxx: mcp23017_1
#      number: 10
#      mode:
#        input: true
#        pullup: false
#      inverted: $sensor_inverted
#    filters:
#      - delayed_on_off: $sensor_debounce_time

  # Zone 04 Input
  - platform: gpio
    name: 4_OfficeWindow
    id: zone4
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_1
      number: 11
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 05 Input
  - platform: gpio
    name: 5_TV_RM_Window1
    id: zone5
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_1
      number: 12
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 06 Input
  - platform: gpio
    name: 6_DoorToGarage
    id: zone6
    icon: mdi:door
    pin:
      mcp23xxx: mcp23017_1
      number: 13
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - logger.log:
            format: "Old state was %s"
            args: ['x_previous.has_value() ? ONOFF(x_previous) : "Unknown"']
        - logger.log:
            format: "New state is %s"
            args: ['x.has_value() ? ONOFF(x) : "Unknown"']
        - mqtt.publish:
            topic: hornet-nest-3cc06c/lastzone
            retain: True
            payload:  !lambda |-
                // return ;
                char buf[128];
                sprintf(buf, "Zone %.2f", x.name);
                return buf;  

  # Zone 07 Input
  - platform: gpio
    name: 7_LivingRoomWin
    id: zone7
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_1
      number: 14
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 08 Input
  - platform: gpio
    name: 8_ClarkWindow
    id: zone8
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_1
      number: 0
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 09 Input
  - platform: gpio
    name: 9_GarageWindow
    id: zone9
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_1
      number: 1
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 10 Input
  - platform: gpio
    name: 10_MavRoomWd
    id: zone10
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_1
      number: 2
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 11 Input
  - platform: gpio
    name: 11_BackDoor
    id: zone11
    icon: mdi:door
    pin:
      mcp23xxx: mcp23017_1
      number: 3
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 12 Input
  - platform: gpio
    name: 12_Master_MD_Window
    id: zone12
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_1
      number: 4
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 13 Input
  - platform: gpio
    name: 13_LivingRoom_Motion
    id: zone13
    icon: mdi:motion-sensor
    pin:
      mcp23xxx: mcp23017_1
      number: 5
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 14 Input
#  - platform: gpio
#    name: Zone 14
#    id: zone14
#    pin:
#      mcp23xxx: mcp23017_1
#      number: 6
#      mode:
#        input: true
#        pullup: false
#      inverted: $sensor_inverted
#    filters:
#      - delayed_on_off: $sensor_debounce_time
  # End MCP23017 Chip number 1
