binary_sensor:

  # Start MCP23017 Chip number 1 - 14 zones
  # Zone 01 Input
  - platform: gpio
    id: zone1
    name: Test
    state_topic: ${name}/binary_sensor/zone1
    pin:
      mcp23xxx: mcp23017_1
      number: 8
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 02 Input
  - platform: gpio
    name: Zone 02
    id: zone2
    pin:
      mcp23xxx: mcp23017_1
      number: 9
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 03 Input
  - platform: gpio
    name: Zone 03
    id: zone3
    pin:
      mcp23xxx: mcp23017_1
      number: 10
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 04 Input
  - platform: gpio
    name: Zone 04
    id: zone4
    pin:
      mcp23xxx: mcp23017_1
      number: 11
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 05 Input
  - platform: gpio
    name: Zone 05
    id: zone5
    pin:
      mcp23xxx: mcp23017_1
      number: 12
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 06 Input
  - platform: gpio
    name: Zone 06
    id: zone6
    pin:
      mcp23xxx: mcp23017_1
      number: 13
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 07 Input
  - platform: gpio
    name: Zone 07
    id: zone7
    pin:
      mcp23xxx: mcp23017_1
      number: 14
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 08 Input
  - platform: gpio
    name: Zone 08
    id: zone8
    pin:
      mcp23xxx: mcp23017_1
      number: 0
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 09 Input
  - platform: gpio
    name: Zone 09
    id: zone9
    pin:
      mcp23xxx: mcp23017_1
      number: 1
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 10 Input
  - platform: gpio
    name: Zone 10
    pin:
      mcp23xxx: mcp23017_1
      number: 2
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 11 Input
  - platform: gpio
    name: Zone 11
    pin:
      mcp23xxx: mcp23017_1
      number: 3
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 12 Input
  - platform: gpio
    name: Zone 12
    pin:
      mcp23xxx: mcp23017_1
      number: 4
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 13 Input
  - platform: gpio
    name: Zone 13
    pin:
      mcp23xxx: mcp23017_1
      number: 5
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 14 Input
  - platform: gpio
    name: Zone 14
    pin:
      mcp23xxx: mcp23017_1
      number: 6
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time
  # End MCP23017 Chip number 1
