binary_sensor:

  # Start MCP23017 Chip number 1 - 14 zones
  # Zone 01 Input
  - platform: gpio
    id: zone1
    name: 1_MasterBathWd
    state_topic: ${name}/binary_sensor/zone1/state
    pin:
      mcp23xxx: mcp23017_1
      number: 8
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time
    #on_state:
      #then:
        #- lambda: |-
        #    id(last_zone) == "Zone 1";
        #- mqtt.publish:
        #    topic: ${name}/lastzone
        #    payload: "Zone 1"
    #on_press:
    #  - mqtt.publish:
    #      topic: ${name}/lastzone
    #      payload: "Zone {{name}}"
          
  # Zone 02 Input
  - platform: gpio
    name: 2_TVBackDoor
    id: zone2
    pin:
      mcp23xxx: mcp23017_1
      number: 9
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 03 Input
  - platform: gpio
    name: Zone 03
    id: zone3
    pin:
      mcp23xxx: mcp23017_1
      number: 10
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 04 Input
  - platform: gpio
    name: 4_OfficeWindow
    id: zone4
    pin:
      mcp23xxx: mcp23017_1
      number: 11
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 05 Input
  - platform: gpio
    name: 5_TV_RM_Window1
    id: zone5
    pin:
      mcp23xxx: mcp23017_1
      number: 12
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 06 Input
  - platform: gpio
    name: 6_DoorToGarage
    id: zone6
    pin:
      mcp23xxx: mcp23017_1
      number: 13
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 07 Input
  - platform: gpio
    name: 7_LivingRoomWin
    id: zone7
    pin:
      mcp23xxx: mcp23017_1
      number: 14
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 08 Input
  - platform: gpio
    name: 8_ClarkWindow
    id: zone8
    pin:
      mcp23xxx: mcp23017_1
      number: 0
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 09 Input
  - platform: gpio
    name: 9_GarageWindow
    id: zone9
    pin:
      mcp23xxx: mcp23017_1
      number: 1
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 10 Input
  - platform: gpio
    name: 10_MavRoomWd
    id: zone10
    pin:
      mcp23xxx: mcp23017_1
      number: 2
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 11 Input
  - platform: gpio
    name: 11_BackDoor
    id: zone11
    pin:
      mcp23xxx: mcp23017_1
      number: 3
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 12 Input
  - platform: gpio
    name: 12_Master_MD_Window
    id: zone12
    pin:
      mcp23xxx: mcp23017_1
      number: 4
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 13 Input
  - platform: gpio
    name: 13_LivingRoom
    id: zone13
    pin:
      mcp23xxx: mcp23017_1
      number: 5
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 14 Input
  - platform: gpio
    name: Zone 14
    id: zone14
    pin:
      mcp23xxx: mcp23017_1
      number: 6
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time
  # End MCP23017 Chip number 1
