binary_sensor:

  # Start MCP23017 Chip number 2 - 14 zones
  # Zone 15 Input
  - platform: gpio
    id: zone15
    name: 15_KitchenWin1
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_2
      number: 8
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 16 Input
  - platform: gpio
    id: zone16
    name: 16_Master_WindowSide
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_2
      number: 9
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 17 Input
  - platform: gpio
    id: zone17
    name: 17_KitchenDoubleWindow
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_2
      number: 10
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 18 Input
  - platform: gpio
    id: zone18
    name: 18_TVRoom_Window2
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_2
      number: 11
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 19 Input
  - platform: gpio
    id: zone19
    name: FrontDoor
    icon: mdi:door
    pin:
      mcp23xxx: mcp23017_2
      number: 12
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 20 Input
  - platform: gpio
    id: zone20
    name: 20_DiningRoomWindow
    icon: mdi:window-closed
    pin:
      mcp23xxx: mcp23017_2
      number: 13
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 21 Input
  - platform: gpio
    id: zone21
    name: 21_GarageDoorBG
    icon: mdi:garage
    pin:
      mcp23xxx: mcp23017_2
      number: 14
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 22 Input
  - platform: gpio
    id: zone22
    name: 22_GarageDoorSM
    icon: mdi:garage
    pin:
      mcp23xxx: mcp23017_2
      number: 0
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 23 Input
  - platform: gpio
    id: zone23
    name: 23_EllieGlassBreak
    icon: mdi:glass-fragile
    pin:
      mcp23xxx: mcp23017_2
      number: 1
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 24 Input
  - platform: gpio
    id: zone24
    name: 24_MavGlassBreak
    icon: mdi:glass-fragile
    pin:
      mcp23xxx: mcp23017_2
      number: 2
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 25 Input
  - platform: gpio
    id: zone25
    name: 25_ClarkGlassBreak
    icon: mdi:glass-fragile
    pin:
      mcp23xxx: mcp23017_2
      number: 3
      mode:
        input: true
        pullup: false
      inverted: $sensor_inverted
    filters:
      - delayed_on_off: $sensor_debounce_time

  # Zone 26 Input
#  - platform: gpio
#    name: Zone 26
#    pin:
#      mcp23xxx: mcp23017_2
#      number: 4
#      mode:
#        input: true
#        pullup: false
#      inverted: $sensor_inverted
#    filters:
#      - delayed_on_off: $sensor_debounce_time

  # Zone 27 Input
 # - platform: gpio
 #   name: Zone 27
 #   pin:
 #     mcp23xxx: mcp23017_2
 #     number: 5
 #     mode:
 #       input: true
 #       pullup: false
 #     inverted: $sensor_inverted
 #   filters:
 #     - delayed_on_off: $sensor_debounce_time

  # Zone 28 Input
#  - platform: gpio
#    name: Zone 28
#    pin:
#      mcp23xxx: mcp23017_2
#      number: 6
#      mode:
#        input: true
#        pullup: false
#      inverted: $sensor_inverted
#    filters:
#      - delayed_on_off: $sensor_debounce_time
  # End MCP23017 Chip number 2
