substitutions:
  warning_beep_index: '1'
  warning_beep_name: Warning Beep
  warning_beep_shared: 'false'
  warning_beep_internal_only: 'false'
  warning_beep_pulse_time: 100ms
  warning_beep_pause_time: 130ms

script:
  - id: error_tone_${warning_beep_index}
    then:
      - output.turn_on: buzzer_output
      - delay: 60ms
      - output.turn_off: buzzer_output
      - delay: 50ms
      - output.turn_on: buzzer_output
      - delay: 60ms
      - output.turn_off: buzzer_output
      - delay: 50ms
      - output.turn_on: buzzer_output
      - delay: 60ms
      - output.turn_off: buzzer_output

light: 
  - id: warning_beep_${warning_beep_index}
    name: ${warning_beep_name}
    platform: binary
    output: buzzer_output
    effects:
      - strobe:
          colors:
            - state: true
              duration: 100ms
            - state: false
              duration: 130ms
    internal: ${warning_beep_internal_only}
